### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by INTJT** [INTJT/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by PES42** [comment]
Rostyslav Suchkov

Greetings, earthlings! I'm a beginner 👨‍💻.
I have been familiar with huge IT world for 2 years.
I'm interested in deep learning and application/game/web development.

Make yourselves at home, folks!
