### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by INTJT** [INTJT/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by PES42** [comment]
Telegram: https://t.me/intjtlmao
GitHub: https://github.com/INTJT
Mail: intjtlmao@gmail.com
