### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by INTJT** [INTJT/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by PES42** [comment]
### Life
* 05.08.2002 - Birth
  * It was a rainny day
* 2008-2019 - Schoolboy
	Brrr
* 2019-Now - Student
  * Surprisingly they teach something

### Education
* Fall 2019 - C++
  * Old-school 😎
* Winter-spring 2020 - Python
  * Ok, but syntax is disgusting 🤢
* Summer 2020 - Deep Learning
  * The neural network learns from its mistakes, but we do not 🥁
* Fall 2020 - C#
  * Perfect ❤️❤️❤️
* Winter 2021 - JavaScript
* Spring 2021 - Java
  * Return to patterns
* Spring 2021 - Scala

### Projects
* Spring 2020 - Sokoban (C++)
  * Brute force💪
* Fall 2020 - Human Resource Machine (C#)
  * Latent assembler
* Now - Game of Life editor (Python)
  * Glyder kingdom
* Now - Heven (messenger, React & Java)
  * Someday I will definitely finish this project...
