### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by INTJT** [INTJT/homepage#6]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by PES42** [comment]
Rostyslav Suchkov (INTJT)

Greetings, earthlings! I'm a beginner 👨‍💻.
I have been familiar with huge IT world for 2 years.
I'm interested in deep learning and application / game / web development.
