### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by INTJT** [INTJT/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by PES42** [comment]
### Interests
* Deep learning
* Web
* Phylosophy
* The Quantym Physics
* Anime
* Chess
* Swimming

### Languages
* English
* Russian
* Ukrainian

### Programming languages
* Java
* JavaScript
* C#
* C++
* Python
* Scala

### Experience
* JavaFX, Tomcat
* Node.js, React.js, Redux
* WinForms, WPF
* Flusk, Tkinter, PyQt5
* Unity
* Oracle, Microsoft SQL Server, MongoDB, SQLite

### Favorite computer-game genres
* RPG
* Rogue-like
* Strategy
* Sandbox
* Shooter

### Like
* Cofee
* Pasta
* Sunday
* Fall
* Silence
* Perfectionism

### Dislike
* Alcohol
* Missing sock
* Shaving
