### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by INTJT** [INTJT/homepage#8]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by PES42** [comment]
Timeline

    Global:
        
        05.08.2002 - Birth
            It was a rainny day
        2008 - 2019 - Schoolboy
            Brrr
        2019 - now - Student (NURE)
            Surprisingly they teach something

    Education:

        fall 2019 - C++
            Old-school
        winter-spring 2020 - Python
            Ok, but syntax is disgusting 🤮
        summer 2020 - Deep Learning
            The neural network learns from its mistakes, but we do not.
        fall 2020 - C#
            Perfect ❤️❤️❤️
        winter 2021 - JavaScript
            this...
        spring 2021
            Java
                Return to patterns
            Scala
                Strange elephanguin 🐘 🐧

    Projects:

        spring 2020 - Sokoban (C++)
            Brute force
        fall 2020 - Human Resource Machine clone (C#)
            Latent assembler
        now:
            Heven (messenger, React & Java)
                Someday I will definitely finish this project...
            Game of Life editor (Python)
                Glyder kingdom
